# Using  .github/workflows/helm-publish.yaml instead for now
steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'cp', '-r', 'charts*', 'gs://statefun-charts/']
  # - name: 'gcr.io/cloud-builders/docker'
    # args: ['build', '-t', 'gcr.io/$PROJECT_ID/statefun-bla', '.']

# images:
  # - 'gcr.io/$PROJECT_ID/statefun-bla'